name: flutter_wechat
description: A new Flutter project.
version: 1.2.0+1

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 0.1.2
  # 本地偏好设置 https://github.com/flutter/plugins/tree/master/packages/shared_preferences
  shared_preferences: 0.5.3+4
  # 图片缓存 https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: 2.0.0
  # Flutter 常用工具库 https://github.com/Sky24n/flustars
  flustars: 0.2.6+1
  # 事件总线 https://github.com/marcojakob/dart-event-bus
  event_bus: 1.0.1
  # 路由管理 https://github.com/theyakka/fluro
  fluro: 1.6.3
  # Flutter 轮播图 https://github.com/best-flutter/flutter_swiper
  flutter_swiper: 1.1.6
  # Flutter 屏幕适配 https://github.com/OpenFlutter/flutter_screenutil
  flutter_screenutil: 0.6.0
  # 获取App信息 https://github.com/flutter/plugins/tree/master/packages/package_info
  package_info: 0.4.0+10
  # WebView插件 https://github.com/flutter/plugins/tree/master/packages/webview_flutter
  webview_flutter: 0.3.15+1
  # Flutter 城市列表，联系人列表，索引&悬停 https://github.com/flutterchina/azlistview
  azlistview: 0.1.2
  # Dart 汉字转拼音 https://github.com/flutterchina/lpinyin
  lpinyin: 1.0.7
  # 展示svg图片 https://github.com/dnfield/flutter_svg
  flutter_svg: 0.17.2
  # 图片浏览器 https://github.com/renancaraujo/photo_view
  photo_view: 0.9.2
  # 侧滑删除 https://github.com/letsar/flutter_slidable
  flutter_slidable: 0.5.4
  # 状态共享 https://github.com/rrousselGit/provider
  provider: 4.0.3
  # 控制屏幕旋转 https://github.com/sososdk/flutter_orientation
  orientation: 1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/login/
    - assets/images/new_feature/
    - assets/images/mainframe/
    - assets/images/contacts/
    - assets/images/search/
    - assets/images/default/
    - assets/images/arrow/
    - assets/images/tabbar/
    - assets/images/about_us/
    - assets/images/ads/
    - assets/images/bg/
    - assets/images/discover/
    - assets/images/profile/
    - assets/images/radio/
    - assets/images/loading/
    - assets/images/input/
    - assets/images/moments/
    - mock/
